### ISSUE TITLE
ERROR downloading module

### ISSUE THREAD

**Issue by shai73** [pnlbwh/nifti-snapshot#1]
I am trying to run randomise_summary.py but I need this nifti-snapshot module. On my university's server I download:

```
bash-4.1$ python3 -m pip install nifti_snapshot
```

but get error:
```
Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement nifti_snapshot (from versions: none)
ERROR: No matching distribution found for nifti_snapshot
```

**Comment by kcho** [comment]
Hi @shai73 

`pip install` is not ready yet for the `nifti_snapshot`. Please try installing through `git clone` and adding it to the `PYTHONPATH`. 

Example command (if you're using unix)
```
mkdir /home/<YOURID>/software  # directory to download nifti_snapshot
cd /home/<YOURID>/software
git clone https://github.com/pnlbwh/nifti-snapshot  
echo "export PYTHONPATH=${PYTHONPATH}:/home/<YOURID>/software/nifti-snapshot/nifti_snapshot" >> ~/.bashrc
```

**Comment by diogenesbispo** [comment]
Hi kcho.
I am unable to access the module: 'nifti_snapshot.nifti_snapshot_utils'.
Do you have any suggestion?

>>python3 /Users/diogenesbispo/Documents/pnl_randomise/lib/randomise_summary.py
Importing modules
Traceback (most recent call last):
  File "/Users/diogenesbispo/Documents/pnl_randomise/lib/randomise_summary.py", line 8, in <module>
    from randomise_corrp import run_randomise_summary_basics, run_atlas_query
  File "/Users/diogenesbispo/Documents/pnl_randomise/lib/randomise_corrp.py", line 11, in <module>
    from randomise_figure import CorrpMapFigure
  File "/Users/diogenesbispo/Documents/pnl_randomise/lib/randomise_figure.py", line 9, in <module>
    import nifti_snapshot.nifti_snapshot as nifti_snapshot
  File "/Users/diogenesbispo/Documents/nifti-snapshot/nifti_snapshot/nifti_snapshot.py", line 10, in <module>
    from nifti_snapshot.nifti_snapshot_utils import get_nifti_data, get_nifti_img_data
ModuleNotFoundError: No module named 'nifti_snapshot.nifti_snapshot_utils'; 'nifti_snapshot' is not a package

**Comment by kcho** [comment]
Hi @diogenesbispo,

`nifti_snapshot` is a requirement package for `pnl_randomise`. You can install the package by following the lines that I added to the issue linked below.

https://github.com/pnlbwh/nifti-snapshot/issues/2#issuecomment-912939582

**Comment by kcho** [comment]
[Slowly getting there but here is some update on nifti-snapshot, which is one of the dependencies of randomise_summary https://nifti-snapshot.readthedocs.io/en/latest/](https://github.com/pnlbwh/nifti-snapshot/issues/3#issuecomment-1005989590)
