### ISSUE TITLE
Script issues after Installation

### ISSUE THREAD

**Issue by hbaagil** [pnlbwh/nifti-snapshot#3]
Hi Kevin, after installation following the README.md file, nothing happens when I run randomise_summary.py. I have just tried to follow the lines above to export to PATH but it doesn't seem to be working either. When I do nifti_snapshot -h, it says command not found. Do you have any suggestions what I can do? 

Thank you for your help in advance!
Hamzah

**Comment by kcho** [comment]
Hi @hbaagil,

These path problems will be solved once I get more time in making the whole script fully installable through `pip`. I'll definitely update you once I do.

In the mean while,
> When I do nifti_snapshot -h, it says command not found. 

It seems like the directory where you have installed `nifti_snapshot` is not under your $PATH variable. 
Try 
```
mkdir ~/scripts
cd ~/scripts
git clone https://github.com/pnlbwh/nifti-snapshot
cd ~/scripts/nifti-snapshot
pip install -r requirements.txt

# path settings : add the two lines below to your ~/.bashrc and execute `source ~/.bashrc`
export PYTHONPATH=${PYTHONPATH}:~/scripts/nifti-snapshot
export PATH=${PATH}:~/scripts/nifti_snapshot/scripts
```

I'd also search for `how to add a directory to PATH` in google.

Kevin

**Comment by kcho** [comment]
@hbaagil Slowly getting there but here is some update on nifti-snapshot documentation https://nifti-snapshot.readthedocs.io/en/latest/

Now it support `pip install nifti_snapshot`, so have a go and let me know please!
